#!/bin/bash

set -euo pipefail

# Root level functions requiring password for uefi-manager

cleanup_temp() {
    :
}

copy_log() {
    :
}

write_checkfile() {
    touch /etc/uefi-stub-installer.chk
}

main() {
    case "$1" in
        copy_log)
            copy_log;;
        cleanup_temp)
            cleanup_temp;;
        write_checkfile)
            write_checkfile;;
        *)
            echo "Error: unknown subcommand: $1" >&2
            return 1;;
    esac
}

main "$@"
